[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nvhtop-tui"
version = "0.1.0"
authors = [
  { name="Vishnu K", email="vishnuk@example.com" },
]
description = "A htop-like utility for NVIDIA GPUs implemented in Python using Textual and pynvml"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "nvidia-ml-py",
    "textual",
    "psutil",
]

[project.scripts]
nvhtop-tui = "main:run"

[tool.setuptools]
py-modules = ["main", "monitor"]
